language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.1
    - android-27

script: ./gradlew clean --refresh-dependencies gateway-android:lintRelease gateway-android:testReleaseUnitTest gateway-android:assembleRelease gateway-android:androidSourcesJar gateway-android:androidJavadocsJar gateway-android:generatePomFileForAarPublication

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew gateway-android:bintrayUpload
  on:
    branch: master
